spring:
  application:
    name: netflix-zuul-api-gateway-server
  # EXPORTING TRACING INFO TO ZIPKIN SERVER
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka