spring:
  application:
    name: currency-conversion-service
  # EXPORTING TRACING INFO TO ZIPKIN SERVER
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8100

#currency-exchange-service:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka