spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/git-localconfig-repo/limits-service.yml

server:
  port: 8888